### ISSUE TITLE
`expr: syntax error`

### ISSUE THREAD

**Issue by jimfleming** [pindexis/qfc#10]
Using iTerm2 on OS X I get this error when pressing "Enter" on a highlighted result: `expr: syntax error`.

**Comment by slowkow** [comment]
This is due to the use of `expr` in `bin/qfc.sh`. See here: http://tldp.org/LDP/abs/html/arithexp.html

I fixed it by changing two lines: https://github.com/pindexis/qfc/pull/13

~~`qfc` still doesn't work for me, and I'm guessing that this might be because I use [vi mode for input](https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html#Readline-Init-File-Syntax) instead of the default emacs mode. I can't quite understand how the code works, so I'm not sure if this is the problem or not.~~

It seems that `qfc` started working when I opened a new shell. Not sure why it failed for some time. It would bring up the menu and I could select an option, but it would not insert the selected text. Now it works. Weird.
