### ISSUE TITLE
Doesn't seem to work with ZSH

### ISSUE THREAD

**Issue by wesbos** [pindexis/qfc#2]
See this video:

http://wes.io/byY4

**Comment by pindexis** [comment]
Thank you for trying the tool,
I think you're using iterm, right?
if that's the case, that issue is due to a bug in iterm actually,
I already filled an issue 20 days ago. The bug has been fixed in the 2.9 beta release.
https://gitlab.com/gnachman/iterm2/issues/3617

**Comment by nicholasc** [comment]
I'm experiencing the same issue on Kubuntu using Konsole and the latest version of zsh.

**Comment by pindexis** [comment]
@nicholasc , 
Thanks for reporting, 
The behavior seen is because Konsole doesn't support all Ansi Movement escape codes (https://en.wikipedia.org/wiki/ANSI_escape_code). Specifically, the "Cursor Horizontal Absolute" code.

I've switched to simulate that using only Ansi.sys escape codes which should be supported in both Konsole and iterm 2.

@wesbos , @nicholasc : can you please try out pulling and confirming that everything works fine. Thanks

**Comment by nicholasc** [comment]
Pulled and it's working fine. Good work!
I'll test on iTerm tomorow at work and let you know.
Thanks.

**Comment by nicholasc** [comment]
Works fine with recommended ITerm 2.1.1
I think this issue can be closed.
